server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice   #微服务名称
#  profiles:
#    active: dev #开发环境
  cloud:
    nacos:
      server-addr: localhost:8848 #配置nacos端口
      discovery:
        cluster-name: HZ  # 配置集群名称，也就是机房位置，例如：HZ，杭州
#      config:
#        file-extension: yaml  #后缀名

mybatis:
  type-aliases-package: cn.ffideal.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.ffideal: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/

fegin:
  client:
    config:
      default:  # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
        loggerLevel: FULL #  日志级别
  httpclient:
    enable: true  # 开启feign对HttpClient的支持
    max-connections: 200  # 最大的连接数
    max-connections-per-route: 50   # 每个路径的最大连接数

