server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: userservice
        # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
        uri: lb://userservice # 路由的目标地址 lb就是负载均衡load balance，后面跟服务名称
        predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
          - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        filters:  # 过滤器
          - AddRequestHeader=Truth, ffideal # 添加请求头
      default-filters:  # 默认过滤器，会对所有的路由请求都生
        - AddRequestHeader=Truth, ffideal # 添加请求头


